### ISSUE TITLE
WTForms 2.0 breaks forms

### ISSUE THREAD

**Issue by Epithumia** [veekun/spline-pokedex#104]
The major update to WTForms from 1.x to 2.x breaks all the search forms. As far as I can tell, there isn't a 5 minute fix, and the easiest solution at the moment is to force a version requirement so that wtforms <=1.0.5 is used.

See http://paste.airelle.info/view/140608.010022.x5rmrs4a for a traceback and https://github.com/mrjoes/flask-admin/issues/541 for a similar issue.

**Comment by magical** [comment]
Ugh.

**Comment by magical** [comment]
This turned out to be not that hard to fix (i think; still need to run tests).
